type TechIcons = {
  [key: string]: string;
};

export const techIcons: TechIcons = {
  js: "/logos/js/js.svg",
  nodejs: "/logos/nodejs/nodejs.svg",
  express: "/logos/expressjs/expressjs-wordmark.svg",
  nextjs: "/logos/nextjs/nextjs.svg",
  ts: "/logos/ts/ts.svg",
  reactjs: "/logos/reactjs/reactjs.svg",
  tailwind: "/logos/tailwind/tailwind.svg",
  python: "/logos/python/python.svg",
  fastapi: "/logos/fastapi/fastapi-icon.svg",
  postgresql: "/logos/postgresql/postgresql.svg",
  uvicorn: "/logos/uvicorn/uvicorn.svg",
  spacyllm: "/logos/spacyllm/SpaCy_logo.svg",
  langchain: "/logos/langchain/langchain-logo.svg",
  llamaindex: "/logos/llamaindex/LlamaSquareBlack.svg",
  neo4j: "/logos/neo4j/neo4j.svg",
  shadcn: "/logos/shadcn/shadcn-logo.svg",
  openai: "/logos/openai/openai-icon.svg",
  socketio: "/logos/socketio/socket.io.svg",
  jest: "/logos/jest/jest.svg",
  // husky: "/logos/postgresql/postgresql.svg",
  // supertest: "/logos/postgresql/postgresql.svg",
  // pgformat: "/logos/postgresql/postgresql.svg",
  vite: "/logos/vite/vitejs.svg",
  axios: "/logos/axios/axios.svg",
  pygame: "/logos/pygame/pygame-logo.svg",
  flask: "/logos/flask/flask.svg",
  webrtc: "/logos/webrtc/webrtc.svg",
  streamlit: "/logos/streamlit/streamlit.svg",
  weaviate: "/logos/weaviate/weaviate-nav-logo-light.svg",
  aws: "/logos/aws/aws.svg",
  css: "/logos/css/css.svg",
  html: "/logos/html/html.svg",
  mongodb: "/logos/mongodb/mongodb.svg",
  javascript: "/logos/javascript/javascript.svg",
};
